### ISSUE TITLE
Special character not working 

### ISSUE THREAD

**Issue by jstgnkl** [brewk/wowspreadsheet#13]
When importing my guild in the spreadsheet 1 character does get processed because of the special character in his name. 

http://i.imgur.com/y76COea.png

Is there a way I can fix this manually?

Thank you for making this awesome spreadsheet. It has been a great help for our guild!

**Comment by brewk** [comment]
Special characters shouldn't be a problem, the weird thing is.. there's no errors! Hmm.. Is this by chance on row 11 on the "With Counters" Sheet on the manual version? I just added this sheet the other day and looking at it now.. for what ever reason the row 11 doesn't seem to have the formulas in both Columns D and F. If you select the cell above in row 10 for each of these columns, you should see a little blue box in the lower right hand corner, you can grab and pull that down and it should create the formula. Let me know if that fixes it! I've fixed it on the template version.

**Comment by jstgnkl** [comment]
I am not sure if we are talking about the same sheet now. I think I am using the automatic guild roster sheet?

https://docs.google.com/spreadsheets/d/1hKAGn5BKjtJN7p6fXRhXbti6zQN8a9Vey-RD_sVFFKA/edit#gid=1751823567

I think you can see it from that link aswell. Thanks for the fast reply!

**Comment by brewk** [comment]
It appears to be the same issue, which is weird because I don't see the formulas missing on the template, but clearly it's related to the other thing i described. 

Anyway: Quickest way to fix is just delete row 13. It'll repull the roster and Skytté will be working correctly. I made a copy of yours and tested and it worked.

**Comment by jstgnkl** [comment]
Deleted it and it worked yes. Thank you very much! :)
