### ISSUE TITLE
Display total AP with thousands seperators

### ISSUE THREAD

**Issue by AntoineHalys** [brewk/wowspreadsheet#14]
Hi,

This is a small function I added:
`function numberWithCommas(x) {
    return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
}`

I call it at line 1058:
`                    artifactRank = artifactRank + " | AP: " +  numberWithCommas(toon.achievements.criteriaQuantity[i]);`

I makes the total AP more readable

Rgds

**Comment by brewk** [comment]
I've added this in, thanks for the help :)
