### ISSUE TITLE
Army of the Light tracking?

### ISSUE THREAD

**Issue by steev** [brewk/wowspreadsheet#16]
I tried to add it myself (basically copying the Nightfallen tracker), however it seems like the reputation id 2165 ( http://www.wowhead.com/faction=2165/army-of-the-light ) is not correct - any non-pandaren Alliance toons report back as hated. Any Pandaren Alliance, or Horde toons properly report back their reputation standing.

**Comment by meltinglava** [comment]
Also tested with my alliance pandaren monk and it reported honored with army of the light

**Comment by steev** [comment]
Confirming that @meltinglava's pull request does allow it to work properly!
