### ISSUE TITLE
7/8 All Done!

### ISSUE THREAD

**Issue by brewk** [brewk/wowspreadsheet#35]
7/8 being marked as All done! in mythics section, possibly pulled.
User who reported  it initially:  'I think I see what that 7/8 mythic deal was. It's pulling from the Mythic+, whereas we're only on Mythic, so it's old mythic content'

**Comment by SKSniperSK** [comment]
Code does filter on current expansion and does also a lookup against a hard-coded list of current dungeons, so old content is very unlikely to have an impact.
We will need some samples of this to further investigate, currently from only looking at the code I can't see a reason for this to happen.

**Comment by brewk** [comment]
fixed by @SKSniperSK  remotely 👍
