### ISSUE TITLE
Inspection Tab Errors when no progression

### ISSUE THREAD

**Issue by brewk** [brewk/wowspreadsheet#46]
need logic to prevent the N/As from causing errors

**Comment by chatterchats** [comment]
Column T functions
=IF(AND(ISNUMBER(R18), ISNUMBER(S18)), R18/S18*10)
=IF(AND(ISNUMBER(R19), ISNUMBER(S19)), R19/S19*10)
=IF(AND(ISNUMBER(R20), ISNUMBER(S20)), R20/S20*10)
=IF(AND(ISNUMBER(R21), ISNUMBER(S21)), R21/S21*10)

Column U functions
=IF(T18=FALSE, "", concat(concat(" [", concat(REPT("|",T18*2), rept(" ", max(0, 20-T18*2)))), "] "))
=IF(T19=FALSE, "", concat(concat(" [", concat(REPT("|",T19*2), rept(" ", max(0, 20-T19*2)))), "] "))
=IF(T20=FALSE, "", concat(concat(" [", concat(REPT("|",T20*2), rept(" ", max(0, 20-T20*2)))), "] "))
=IF(T21=FALSE, "", concat(concat(" [", concat(REPT("|",T21*2), rept(" ", max(0, 20-T21*2)))), "] "))

Column AA
=IF(AND(ISNUMBER(Y18), ISNUMBER(Z18)), Y18/Z18*10)
=IF(AND(ISNUMBER(Y19), ISNUMBER(Z19)), Y19/Z19*10)
=IF(AND(ISNUMBER(Y20), ISNUMBER(Z20)), Y20/Z20*10)
=IF(AND(ISNUMBER(Y21), ISNUMBER(Z21)), Y21/Z21*10)

Column AB
=IF(AA18=FALSE, "", concat(concat(" [", concat(REPT("|",AA18*2), rept(" ", max(0, 20-AA18*2)))), "] "))
=IF(AA19=FALSE, "", concat(concat(" [", concat(REPT("|",AA19*2), rept(" ", max(0, 20-AA19*2)))), "] "))
=IF(AA20=FALSE, "", concat(concat(" [", concat(REPT("|",AA20*2), rept(" ", max(0, 20-AA20*2)))), "] "))
=IF(AA21=FALSE, "", concat(concat(" [", concat(REPT("|",AA21*2), rept(" ", max(0, 20-AA21*2)))), "] "))

Columns L M N, respectively
=IF(NOT(ISNUMBER(U18)), "None", concat(U18,R18))
=IF(NOT(ISNUMBER(U19)), "None", concat(U19,R19))
=IF(NOT(ISNUMBER(U20)), "None", concat(U20,R20))
=IF(NOT(ISNUMBER(U21)), "None", concat(U21,R21))

=IF(NOT(ISNUMBER(Y18)), "None", CONCAT(AB18, Y18))
=IF(NOT(ISNUMBER(Y19)), "None", CONCAT(AB19, Y19))
=IF(NOT(ISNUMBER(Y20)), "None", CONCAT(AB20, Y20))
=IF(NOT(ISNUMBER(Y21)), "None", CONCAT(AB21, Y21))

=IF(NOT(ISNUMBER(Y18)), "0 / 0", concat(concat(Y18, " / "), Z18))
=IF(NOT(ISNUMBER(Y19)), "0 / 0", concat(concat(Y19, " / "), Z19))
=IF(NOT(ISNUMBER(Y20)), "0 / 0", concat(concat(Y20, " / "), Z20))
=IF(NOT(ISNUMBER(Y21)), "0 / 0", concat(concat(Y21, " / "), Z21))

**Comment by brewk** [comment]
fixed with @RTO-Chatter comment data
