### ISSUE TITLE
More stuff on the Inspection Tab

### ISSUE THREAD

**Issue by brewk** [brewk/wowspreadsheet#47]
Inspection tab should have mythic+ info, at the very least! Maybe we can put in a special pvp api call for folks we inspect?

**Comment by chatterchats** [comment]
Layout: https://i.imgur.com/XwCVYFD.png

Cell Q1: `=SPLIT(A2, "-")`
Cell L32: `=VLOOKUP(Q15,Progression!C3:E, 3)`
Cell L33: `=TEXTJOIN(" ", TRUE, "+", ARRAYFORMULA(VLOOKUP($Q$15,'Mythic+'!C:AC,{6,7},FALSE)))`
Cell L34: `=TEXTJOIN(" ", TRUE, "+", ARRAYFORMULA(VLOOKUP($Q$15,'Mythic+'!C:AC,{10,11},FALSE)))`
Cell L35: `=TEXTJOIN(" ", TRUE, "+", ARRAYFORMULA(VLOOKUP($Q$15,'Mythic+'!C:AC,{18,19},FALSE)))`
Cell L36: `=TEXTJOIN(" ", TRUE, "+", ARRAYFORMULA(VLOOKUP($Q$15,'Mythic+'!C:AC,{26,27},FALSE)))`

**Comment by brewk** [comment]
using formulas in @RTO-Chatter comment, thanks!
