### ISSUE TITLE
Oauth error

### ISSUE THREAD

**Issue by BoscoDomingo** [brewk/wowspreadsheet#68]
Hello, after setting up client and ID following the Wiki's instructions, I get this error when refreshing data:
![image](https://user-images.githubusercontent.com/46006784/122684232-7fc12a80-d204-11eb-9538-d54b4ea5fbdb.png)

It would look as though the URL is not being set up correctly? This are my settings:
![image](https://user-images.githubusercontent.com/46006784/122684245-98314500-d204-11eb-8fca-f24e8439fff0.png)

I even refreshed the Client's secret in case it was outdated, but to no avail. Any ideas? Thanks!

**Comment by SKSniperSK** [comment]
For this kind of issue you can get help on our Discord server: https://discord.gg/DvmvR4H
